language: node_js
node_js:
  - 11.6.0
jobs:
  include:
    - stage: test
      name: 'Run Linters'
      script: npm run lint:js
    - stage: test
      name: 'Run tests'
      script: npm run test:coverage
after_success:
  - npx codecov
