language: node_js
node_js:
  - 11.6.0
jobs:
  include:
    - stage: test
      name: 'Run Linters'
      script: npm run lint
    - stage: test
      name: 'Run tests'
      script: npm run test:coverage
    - stage: test
      name: 'CLI'
      script: npm run generate
after_success:
  - npx codecov
