openapi: 3.0.3
info:
  version: 1.1.4
  title: GitHub v3 REST API

paths:
  /public/v1/foos:
    get:
      operationId: getFoos
      tags:
        - Foo
      description: Foo foo foo foo.
      responses:
        "200":
          description: The foos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Foos'
        "422":
          description: A validation error, invalid or missing supplier ID.
  /public/v1/{id}/foos:
    get:
      operationId: getFoosWithID
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      description:
        $ref: "#/paths/~1public~1v1~1foos/get/description"
      tags:
        $ref: "#/paths/~1public~1v1~1foos/get/tags"
      responses:
        $ref: "#/paths/~1public~1v1~1foos/get/responses"